name: chat_app_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  dio: ^5.4.0
  socket_io_client: ^3.1.1
  flutter_secure_storage: ^9.0.0

  flutter_webrtc: ^0.13.1+hotfix.1
  permission_handler: ^11.4.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  get_it: ^8.0.3

  crypto: ^3.0.3
  fast_rsa: ^3.8.5
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
